### PR TITLE
Locked port tests added

### PR DESCRIPTION
**Pull request by shans-westermo**

### CODE REVIEW

**Comment by troglobit** [comment]
In general it looks great!  

Could you add:
 1. A one-liner comment before each test as a short-description
 2. Fix indent depth in all functions (currently mix of leading tabs and spaces)

**Comment by wkz** [comment]
Agree with @troglobit!

Also, please add a check to see if the system supports this feature. Here is an example:
https://github.com/westermo/brist/blob/main/suite/30-stp-vlan.sh#L11-L14

**Comment by troglobit** [comment]
Hi, sorry for the late reply.

The tests basic_locked_port and locked_port_spoofing still seem to fail instead skip in our auto tests here on GitHub.  Could you see if your last commit (Check added if VLAN is not supported) really checks for the locked-port feature properly?

**Comment by troglobit** [comment]
Tests pass!  I'm OK with this if you are, @wkz :)

**Pull request merged**
